:project: Les colons de Catane

= Spécification des exigences

== Introduction 

Ce chapitre décrit les exigences du projet «{project}». Il suit la norme IEEE 830-1998.

L'objectif de ce document est de décrire les spécifications des exigences du projet "{project}" pour les étudiants en génie logiciel.

=== Définitions, acronymes et abréviations

Aucune jusqu'à présent.

=== Public visé et suggestions de lecture

Le public visé par cette spécification sont les développeurs ainsi que les personnes chargées de l'évaluation technique de l'application.

La section <<description>> s'adresse à tous les lecteurs de ce document. Elle permet de bien comprendre le but de cette application. 

La partie <<contrainte>> s'adresse principalement aux développeurs, et défini toutes les bonnes pratiques, les contraintes et les différentes technologies à utiliser pour le développement de cette application. 

La section <<features>> s'adresse une nouvelle fois aux développeurs et aux personnes chargées de l'évaluation technique. Cette section décrit concrètement toutes les fonctionnalitées que doit posséder l'application. 

Enfin, la partie <<nonfunctional>> s'adresse exclusivement aux développeurs.

=== Portée du projet

Le système logiciel à produire est une version simplifiée du jeu de plateau {project}, qui sera désigné par le terme "{project}" dans le présent document.

Le système {project} permettra à des joueurs de différents endroits de s'affronter dans des parties courtes et intensives.

=== Références

. IEEE Standard 830-1993: IEEE Recommended Practice for Software Requirements Specifications

=== Vue d’ensemble 

Le reste de ce document contient une description globale du système logiciel {project} (section <<description>>, les exigences fonctionnelles spécifiques (section <<features>>) et les exigences non-fonctionnelles du système (voir <<nonfunctional>>).

[#description]
== Description générale

=== Perspectives du produit

{project} est un jeu de cartes où plusieurs joueurs s'affrontent.
Le logiciel {project} doit permettre aux joueurs qui sont connectés à Internet d'utiliser leurs appareils connectés pour jouer.
Ainsi, "{project}" est une version électronique en ligne du jeu de cartes.

Bien que le système soit distribué et organisé en différents composants, les joueurs doivent le percevoir comme un seul logiciel.
La figure <<deployment>> présente l'architecture globale du logiciel.
Les joueurs interagissent avec un client Web, qui utilise le protocole HTTP pour communiquer avec (au maximum) un serveur de jeu.
Les serveurs utilisent le protocole TCP/IP pour communiquer avec un serveur de gestion de base de données, qui stocke toutes les données du logiciel.

[#deployment]
.Diagramme de déploiement 
[plantuml]
----
include::partial$DeploymentDiagramsCatan.puml[]
----

=== Fonctionnalités du produit

Le logiciel {project} doit assurer deux fonctions principales :

. Création de jeu : permettre à deux joueurs de se découvrir et de commencer une partie.
. Le jeu{nbsp}: permettre aux joueurs de jouer effectivement à {project} jusqu'à la victoire de l'un d'entre eux.


=== Caractéristiques et classes d'utilisateurs

Le logiciel {project} n'a qu'une seule classe d'utilisateurs : les joueurs.
Les joueurs peuvent avoir différents niveaux : débutants, intermédiaires ou experts.
Cependant, indépendamment de leur niveau, les joueurs doivent utiliser la même interface utilisateur pour jouer les uns contre les autres.
Il doit être possible d'inviter différents joueurs à jouer ensemble.

[#nonfunctional]

[#nonfunctional]


=== Environnement opérationnel

Le logiciel {project} doit fonctionner sur tout système d'exploitation populaire et récent{nbsp}: Linux, Windows, ou MacOS.
Le client Web devrait fonctionner sur tout navigateur Web récent{nbsp}: Firefox, Chrome, Safari, ou Edge.

Il sera installé sur un ordinateur ou un appareil mobile disposant d'une configuration matérielle suffisante pour exécuter les applications et le système d'exploitation. Il sera également compatible avec toutes les versions récentes des systèmes d'exploitation mentionnés ci-dessus.

Le logiciel devra également coexister pacifiquement avec tout autre logiciel ou application installé sur l'ordinateur ou l'appareil mobile, en prenant en compte les éventuelles restrictions de compatibilité et de fonctionnalité.

[#contrainte]
== Contraintes de conception et de mise en œuvre

=== Langages de programmation

. Le serveur de jeu doit être développé en Java (version ≥ 11), en utilisant le https://spring.io [Spring Framework].
. Le client doit être développé en TypeScript (version ≥ 4.0), en utilisant le https://angular.io [Angular Framework].


=== Langage de conception

. Les documents sur le développement du logiciel doivent être écrits dans le format Asciidoc.
. Les diagrammes UML d'analyse, conception et mise en œuvre devront être réalisés en PlantUML.

=== Conception
=== Mise en œuvre

. Les tests dynamiques doivent utiliser JUnit (version >= 5.0) et Jasmine (version >= 3.5.0).
. Le code doit journaliser ses principales opérations en utilisant https://www.slf4j.org [SLF4J].

=== Outils de construction

. Tous les artefacts logiciels doivent utiliser un outil de construction : Maven ou Groovy pour Java, npm pour TypeScript.

=== Outils de développement
=== Bibliothèques et composants logiciels


== Vérification

. Les doubles tests doivent être utilisés pour tester chaque composant indépendamment.
. Chaque test unitaire doit décrire son intention.

== Documentation utilisateur

Aucune documentation utilisateur n'est requise pour la première version du logiciel.

=== Hypothèses et dépendances

Aucun jusqu'à présent.

=== Exigences reportées


Les versions futures du système comprendront l’utilisation d’un mécanisme de persistance de données ainsi que différentes interfaces utilisateur: web, IHM classique, etc. Elles permettront aussi l’accès distant à travers une interface REST.

Les versions futures pourraient permettre de jouer une partie avec plus de deux joueurs (3-4).

== Exigences en matière d'interface externe

=== Interfaces utilisateur

L'interface web du logiciel devra comporter les éléments suivants:

- un champ de saisie pour le nom du joueur
- un bouton pour lancer une partie
- un bouton pour quitter la partie
- plusieurs boutons représentant les actions possibles pour le joueur
- une représentation du plateau de jeu  
- les ressources d'un joueur (nombre de pièces, nombre de points de victoire ...)
- une représentation des cartes en main du joueur adverse


// [NOTE]
// ====
// Décrivez les caractéristiques logiques de chaque interface entre le produit logiciel et les utilisateurs. 

// Il peut s'agir d'exemples d'images d'écran, de normes d'interface graphique ou de guides de style de famille de produits à respecter, de contraintes de disposition des écrans, de boutons et de fonctions standard (p. ex., aide) qui apparaîtront sur chaque écran, de raccourcis clavier, de normes d'affichage des messages d'erreur, etc. 

// Définissez les composants logiciels pour lesquels une interface utilisateur est nécessaire. 
// Les détails de la conception de l'interface utilisateur doivent être documentés dans une spécification d'interface utilisateur distincte.
// ====

=== Interfaces matérielles

Le logiciel n'interagit pas directement avec un quelconque dispositif matériel.

=== Interfaces logicielles

La partie client du logiciel doit fonctionner sur des navigateurs web, tandis que la partie serveur doit interagir avec une base de données par le biais de l'API Java Persistence (JPA).



=== Interfaces de communication

Les communications entre le client et le serveur de jeu doivent utiliser des Websockets.

[#features]
== Exigences fonctionnelles

=== Fonctionnalité Rejoindre une partie

La fonctionnalité Rejoindre une partie permet à un joueur de rejoindre une partie en cours, en fournissant son nom.
Cette fonctionnalité a une priorité moyenne.

==== Séquences de Stimulus/Réponse

La fonctionnalité Rejoindre une partie est déclenchée par l'action de l'utilisateur de cliquer sur le bouton "Rejoindre une partie" de l'interface web.

==== Exigences fonctionnelles
* REQ-1: Le système doit permettre à un joueur de fournir son nom.
* REQ-2: Le système doit permettre à un joueur de rejoindre une partie en cours.
* REQ-3: Le sustème doit vérifier que le nom du joueur est valide.

=== Fonctionnalité Jouer un tour

La fonctionnalité Jouer un tour permet à un joueur de jouer un tour en choisissant quelles actions il veut effectuer.


==== Description et priorité

La fonctionnalité Jouer un tour permet à un joueur de jouer un tour en choisissant quelles actions il veut effectuer, en fonction de ses cartes en main et de la situation de la partie.
Cette fonctionnalité a une priorité moyenne.

==== Séquences de Stimulus/Réponse

La fonctionnalité Jouer un tour est déclenchée par le serveur qui indique au joueur qu'il est son tour de jouer.


==== Exigences fonctionnelles

* REQ-1: Le système doit permettre de communiquer au joueur qu'il est son tour de jouer.
* REQ-2: Le système doit permettre au joueur de choisir une action à effectuer.

=== Fonctionnalité Finir la partie

La fonctionnalité Vérifier fin de partie permet de vérifier si la partie est terminée. Si c'est le cas, le système doit afficher le gagnant, et clôturer la partie.


==== Description et priorité

La fonctionnalité Vérifier fin de partie permet de vérifier si la partie est terminée. Si c'est le cas, le système doit afficher le gagnant, et clôturer la partie.
Cette fonctionnalité a une priorité moyenne.

==== Séquences de Stimulus/Réponse

La fonctionnalité Vérifier fin de partie est déclenchée à chaque fois qu'un joueur joue un tour. Le système vérifie alors si la partie est terminée. Si c'est le cas, le système affiche le gagnant, et clôture la partie.


==== Exigences fonctionnelles

* REQ-1: Le système doit pouvoir vérifier si la partie est terminée.
* REQ-2: Le système doit pouvoir afficher le gagnant de la partie.
* REQ-3: Le système doit pouvoir clôturer la partie.


[#nonfunctional]
== Autres exigences non-fonctionnelles

=== Exigences de concurrence 

. Seul le joueur actif peut modifier les données du jeu de lui même (sans que le serveur lui demande).

=== Exigences de performance 

. Le jeu doit être _jouable_, ce qui signifie que les utilisateurs doivent avoir un retour rapide de leurs actions et que les retards dus aux problèmes de communication/connexion doivent être correctement tenus.
. Le client Web doit pouvoir s'exécuter sur un ordinateur personnel doté de 4 Go de RAM.

=== Exigences d'interopérabilité

. Le logiciel doit être configurable facilement.


=== Exigences de portabilité

. Le logiciel doit fonctionner sur plusieurs appareils ou plateformes.

=== Exigences de sécurité

. Un joueur ne peut pas jouer un tour s'il n'est pas son tour. 
. Un joueur ne peut pas jouer un tour s'il n'est pas connecté au serveur.
. Un joueur ne peut pas jeffectuer une action qui n'est pas autorisée par les règles du jeu.
. Un joueur ne peut pas voir les cartes d'un autre joueur.
. Un joueur ne peut pas jouer à la place d'un autre joueur.

=== Exigences de maintenabilité

. Il doit être possible d'ajouter du contenue supplémentaire facilement (cartes, constructions...).
. Le logiciel doit être lisible et facile à maintenir.
. La source Java doit respecter les directives de Google : https://google-styleguide.googlecode.com/svn/trunk/javaguide.html.
