image:
  name: docker-registry.univ-nantes.fr/sunye-g/docker-antora-assembler
  
pages:
  stage: deploy
  cache:
    paths:
    - .cache/
  script:
  - antora --stacktrace --fetch --cache-dir .cache/antora --attribute page-pagination= --to-dir public antora-playbook.yml
  artifacts:
    paths:
    - public/
