:project: Les colons de Catane
= Architecture

== Introduction

Ce chapitre décrit l'architecture d'une famille de produits, dont le projet {project} en fait partie.

L’objectif de ce document est de décrire choix génériques, qui peuvent s'appliquer à plusieurs projets de ce type.

== Vue physique

=== Dépandances

** Serveur

* Java 16
* Maven v4.0.0
* Spring v5.3.1
* Junit v5.9.1
* Mockito v3.6.0
* Reflections v0.10.2
* Snakeyaml v1.33

** Client

* Angular v15.1.0
* Node v19.3.0

=== Besoins matériels
* 1 à 2 navigateurs web
* 1 serveur d'hébergement

.Diagramme de déploiement (niveau spécification)
[plantuml]
----
include::example$deployment-diagram-example.plantuml[]
----


.Diagramme de déploiement (niveau instance)
[plantuml]
----
include::example$deployment-diagram-example.plantuml[]
----

== Vue de la fiabilité

.Initialisation du système
[plantuml]
----
include::example$ad-initialization.plantuml[]
----

== Vue du développement

.Organisation des modules serveur
[plantuml]
----
include::example$CatanPackageDiagram.puml[]
----

.Organisation des modules client
[plantuml]
----
include::example$CatanClientPackageDiagram.puml[]
----


== Vue logique

[NOTE]
====
L'objectif de la vue logique est de décrire les différents composants qui jouent un rôle commun
dans les différents projets qui respectent une même architecture.
====


== Vue technique : traduction de UML en code source


** Pour chaque instance de package UML, une instance de package Java doit être créée. 
* Leurs noms doivent correspondre. Cependant, contrairement aux packages UML qui ont des noms simples, le nom du package Java contient l'information complète sur le chemin d'accès. 
des noms simples, le nom du package Java contient des informations complètes sur le chemin. La séparation du chemin 
est un point ".". 

**Pour chaque instance de classe UML, une instance de JavaClass doit être créée. 
* Leurs noms doivent correspondre. 
* La référence du paquetage doit correspondre. 
* Les modificateurs doivent correspondre. 

** Pour chaque instance de DataType UML, une instance de PrimitiveType Java doit être créée. 
* Leurs noms doivent correspondre. 
* La référence du paquet doit correspondre. 

** Pour chaque instance d'attribut UML, une instance de champ Java doit être créée. 
* Leurs noms doivent correspondre. 
* Leurs types doivent correspondre. 
* Les modificateurs doivent correspondre. 
* Les classes doivent correspondre.
 
** Pour chaque instance d'opération UML, une instance de méthode Java doit être créée. 
* Leurs noms doivent correspondre. 
* Leurs types doivent correspondre. 
* Les modificateurs doivent correspondre. 
* Les classes doivent correspondre.

Traduit avec www.DeepL.com/Translator (version gratuite)



=== Règles de traduction des types de base

.Traduction des types de base
|===
| UML | Java | TypeScript

| Integer
| Integer
| number

| Boolean
| Boolean
| boolean

| String
| String
| string

| Real
| Double
| number

|===

=== Conventions de codage

** Java
* Les classes et les interfaces utilisent le PascalCase
* Les noms de méthodes et de variables utilisent le camelCase

** Typescript
* Les classes et les interfaces utilisent le PascalCase
* Les noms de fichiers et les pages utilisent le PascalCase
* Les variables utilisent le camelCase

== Conclusion

Le backend a été construit avec une structure modulaire et non cyclique, ce qui signifie qu'il n'y a pas de dépendances entre les différents modules et que chacun peut être facilement remplacé.

