= Conception détaillée

Ce chapitre répond aux différentes exigences non-fonctionnelles du projet «Catane».

L’objectif de ce document est de détailler la spécification des composants, notamment leur structure, ainsi que le comportement de chaque opération fournie par le composants.


== Réponses aux exigences non-fonctionnelles

=== Concurrence

Pour gérer la concurrence, nous avons mis en place un système de verrouillage de l'envois de requête, qui empêche les deux joueurs d'exécuter simultanément des commandes. Ainsi seul le joueur actif peut intéragir avec le serveur.

Cependant il est possible de spécifier qu'une commande n'a pas besoin de posséder le verrou pour pouvoir s'exécuter. C'est notamment utile pour les cas ou le serveur attent une réponse à la suite d'une requête.

=== Performance

Pour améliorer les performances du jeu, nous avons optimisé le code en utilisant des algorithmes efficaces et en réduisant au minimum les appels aux systèmes gérant les données. 

Nous avons également mis en place un système d'identifiant pour nos objets, afin réduire le temps de chargement des données.

=== Interopérabilité

Pour assurer l'interopérabilité du jeu, nous avons utilisé des formats de fichiers standard et des protocoles de communication couramment utilisés dans l'industrie. 

Nous avons également inclus des options de configuration pour permettre aux joueurs de personnaliser leur expérience de jeu en fonction de leurs préférences.


=== Portabilité

Pour rendre le jeu portable, nous avons utilisé des technologies cross-platform permettant de faire fonctionner le jeu sur différents systèmes d'exploitation et appareils.

=== Sécurité

Notre système doit être sécurisé, même si nous ne manipulons pas des données sensibles. Pour cela nous devons vérifier l'identité de l'utilisateur.

N'ayant pas à nous occuper de l'authentification de l'utilisateur nous admettons que le système s'occupant de cela est correct et lui-même sécurisé. Nous admettons également que, quelle que soit la plateforme utilisée (web, logiciel, application) le service d'authentification sera le même pour tous.

=== Maintenanbilité

Pour assurer la maintenabilité du jeu, nous avons adopté une approche de conception modulaire qui permet de mettre à jour ou de remplacer facilement les différentes parties du jeu sans affecter l'ensemble du système. 

Nous avons également fais en sorte de rendre le système extensible. Ainsi, il est  très simple de créer de nouvelles cartes, de rajouter de nouveaux types de routes ou de bâtiments, modifier les règles de constructions etc...

=== Interface utilisateur

La partie interface utilisateur n'a, jusqu'à présent, pas été notre priorité sur ce projet. Ainsi l'interface actuelle n'est que purement visuel et non interactive.

Cependant une interface interactive du plateau a été développé mais n'a pas encore été utilisé comme interface de base.

=== Interface logicielle

Pour faciliter l'intégration du jeu avec d'autres logiciels, nous avons défini des interfaces claires et simples qui spécifient les fonctionnalités et les données disponibles pour les développeurs tiers. 

Nous avons également inclus une documentation complète de nos interfaces, de leurs implémentations et du projet en général.

== Patrons logiciels utilisés

=== Patron de conception Singleton

Le patron de conception Singleton est un patron de conception de logiciel qui garantit qu'une seule instance d'une classe donnée sera créée et qu'il y aura un point d'accès global à cette instance. 

Cela peut être utile lorsque nous avons besoin de garantir qu'il n'y a qu'une seule instance d'une classe dans toute l'application. Ce patron a été utilisé pour créer les différentes stratégies de construction ou de générations de resource des territoires.

=== Patron architectural Strategy

Le patron de conception Strategy est un patron de conception de logiciel qui permet de définir une famille d'algorithmes, de les encapsuler individuellement et de les rendre interchangeables. 

Cela permet à une application de choisir l'algorithme à utiliser à l'exécution, plutôt que de devoir choisir un algorithme spécifique lors de la compilation. Ce patron a été utilisé pour gérer les différentes stratégies de construction ou de générations de resource des territoires.

=== Patron architectural Facade

Le patron de conception Facade est un patron de conception de logiciel qui vise à simplifier l'interface d'un système complexe en fournissant une interface simplifiée à une sous-partie de ce système. 

Le but de ce patron est de rendre le système plus facile à utiliser en masquant la complexité de ses sous-systèmes et en fournissant une interface commune pour accéder à ces sous-systèmes. Ce patron a été utilisé pour nos différents controlleurs. Ces controlleurs fournissent des interfaces simples permettant de manipuler simplement ce dont ce controlleur à la charge.

=== Patron architectural Command

Le patron de conception Command est un patron de conception de logiciel qui vise à encapsuler une requête sous la forme d'un objet, de manière à pouvoir paramétrer des objets avec des comportements différents, enregistrer ces objets et les exécuter ultérieurement. 

Le patron Command permet de découpler l'objet qui envoie la requête de l'objet qui exécute la requête, ce qui rend votre code plus flexible et plus facile à maintenir. Ce patron a été utilisé pour que le client puisse envoyé des requêtes au serveur, et que la partie puisse recevoir cette requête et la traiter.

== Choix techniques - Distribution des processus

Pour cela nous allons donc vous présenter l'environnement général de développement puis énoncer les 4 contraintes que nous avons déterminées de notre logiciel.

Nous avons fais le choix d'utiliser comme environnement de travail l'IDE eclipse.
Pour la raison que nous connaissons tous très bien cette environnement, ce qui nous permet d'avoir tous le même environnement de développement.

Également, cette IDE permet la gestion d'un projet maven ce qui nous sera parfaitement adapté.

Voici les 4 contraintes que nous avons déterminées :

. L'interface graphique.
. La communication vers la base de données.
. La communication entre les machines.
. La sécurité.
