:project: Catane
= Analyse du domaine

== Modèle du domaine

.Classes conceptuelles
[plantuml]
....
include::partial$CatanUMLDiagram.puml[]
....

== Cas d'utilisation

=== Cas d'utilisation "Mise en place d'une partie"

include::partial$UseCaseImplementationCatan.adoc[]

.Diagramme d'activités: Mise en place d'une partie
[plantuml]
....
include::partial$ImplementationActivityDiagramCatan.puml[]
....

=== Cas d'utilisation "Jouer un tour"

include::partial$UseCasePlayRoundCatan.adoc[]

.Diagramme d'activités: Jouer un tour
[plantuml]
....
include::partial$PlayRoundActivityDiagramCatan.puml[]
....

== Activités

=== Préparer le plateau

Les zones mers sont placé aléatoirement, le désert est placé au centre du plateau, les territoires sont placé dans un ordre aléatoire en suivant un chemin en escargot partant du désert. Ensuite les jetons sont placé en suivant le même ordre.

=== Choix d’une couleur

Chaque joueur choisit une couleur parmis le rouge, le orange, le blanc et le bleu

=== Distribution du matériel

Chaque joueur reçoit une fiche Coûts de construction et toutes les pièces de jeu de sa couleur : 5 Colonies, 4 Villes et 15 Routes

=== Placement des premières constructions

Chaque joueur (du plus vieux au plus jeune) place tour à tour une route et une colonie sur le plateau. L'opération est recommencé une deuxième fois dans le sens inverse
Chaque joueur place devant lui ses pièces de jeu restantes. S’il n’y a que 3 joueurs, les pièces de jeu rouges retournent dans la boîte

=== Placement des fiches spéciales et des dés

Les fiches spéciales Route la plus longue et Armée la plus puissante sont placées à côté de la zone de jeu, ainsi que les 2 dés

=== Créer la pioche ressource

Les cartes Ressource sont triées en 5 piles, par type et placées face visible

=== Créer la pioche développement

Les cartes Développement sont mélangées et placées face cachée

=== Distribution de la première production

Chaque joueur reçoit pour sa colonie marquée d’une étoile sa première production

=== Choix du joueur qui débute

Le joueur le plus agée débute la partie

=== Lancer les dés

Le joueur actif lancent les deux dés

*pré-condition*

    Le lanceur est le joueur actif

*post-condition*

    Le résultat est compris entre 2 et 12

=== Commercer avec les joueurs

Le joueur actif peut échanger n'importe qu'elle ressource avec n'importe quel joueur

*pré-condition*

    Les deux joueurs sont d'accord ET

    Les deux joueurs possèdent les ressources

*post-condition*

    Chaque joueur a perdu les ressources qu'il échangeait et a gagné les ressources qui lui était promises

=== Echanger des ressources

Le joueur actif peut échanger plusieurs ressources du même type contre une ressource au Choix

*pré-condition*

    Le joueur possède assez de ressource du même type ET

    La banque possède la ressource que le joueur souhaite

*post-condition*

    Le joueur a perdu ses ressources qu'il échangeait et a gagné la ressource souhaité

=== Construire une route

Le joueur peut construire une route sur un chemin en échange de ressource. Cette route peut uniquement être construite sur un chelin voisin à une route, une colonie ou une ville de sa couleur

*pré-condition*

    Le joueur a les ressource pour construire une route ET

    Un emplacement valide est disponible pour construire la route

*post-condition*

    Le joueur a perdu les ressources liées au coût de construction ET

    Le joueur a placé une route sur le plateau

=== Construire une colonie

Le joueur actif peut installer une nouvelle colonie sur une intersection en échange de ressource. Cette colonie peut uniquement être construite sur une intersection voisine à une route, une colonie ou une ville de sa couleur

*pré-condition*

    Le joueur a les ressource pour construire une colonie ET

    Un emplacement valide est disponible pour construire la colonie

*post-condition*
 
    Le joueur a perdu les ressources liées au coût de construction ET

    Le joueur a placé une colonie sur le plateau

=== Construire une ville

Le joueur actif peut installer une nouvelle ville à la place d'une colonie en échange de ressource. Cette ville peut uniquement être construite sur colonie de sa couleur

*pré-condition*

    Le joueur a les ressource pour construire une ville ET

    Le joueur possède une colonie

*post-condition*

    Le joueur a perdu les ressources liées au coût de construction ET

    Le joueur a retiré une colonie du plateau et y a placé une ville

=== Acheter une carte développement

Le joueur actif peut acheter une carte développement en échange de ressource.

*pré-condition*

    Le joueur a les ressource pour acheter la carte développement ET

    La carte développement est disponible

*post-condition*

    Le joueur a perdu les ressources liées au coût l'achat de la carte développement ET

    Le joueur a possède la carte développement

=== Utiliser une carte développement

Le joueur actif peut utiliser une carte développement

*pré-condition*

    Le joueur possède une carte développement

*post-condition*

    L'effet de la carte développement a été activé

=== Déplacer le voleur

Le joueur actif peut installer déplacer le voleur sur un nouveau territoire

*pré-condition*

    Le joueur a réalisé un 7 aux dés OU

    Le joueur utilise une carte chevalier

*post-condition*

    Le voleur a changé de territoire ET

    Le joueur actif a volé une carte ET

    Un joueur possèdant une colonie adjacente au voleur s'est fait volé une carte

== Opérations

// include::uc-template.adoc[]
