@startuml 'https://plantuml.com/activity-diagram-beta'

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Ce sont toutes les instances de notre jeu de société.
class Joueur
class Partie
class Construction
class Route
class Ville
class Pièce
class Colonie
class Dé
class Territoire
enum TypeTerritoire
class Ressource
enum TypeRessource
class Plateau
class ZoneBatiment
class ZoneRoute
class ZoneConstructible
class Carte
class Développement
class Ressource
class Fiche
class Coût
class Spéciales 
class Progrès
class Chevalier
class CartePV
enum TypeCartePV
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Ici, ce sont toutes nos relations entre nos différentes instances.
Joueur <-- Partie : [3:4]
Joueur <-- Pièce : [0,n]
Joueur --> Carte : [0,n]
Pièce --> Route : [1]
ZoneRoute --> Route : [0,1]
Construction --> Pièce :[1]
Ville --|> Construction
Colonie --|> Construction
ZoneBatiment --> Construction : [0,1]
Dé <-- Plateau : [2]
Ressource <-- Territoire : [1]
Plateau --> Territoire : [19]
Plateau --* Partie
Plateau --> ZoneConstructible
Développement --|> Carte
Ressource --|> Carte
Fiche --|> Carte
Progrès --|> Développement
Chevalier --|> Développement
CartePV --|> Développement
ZoneRoute --|> ZoneConstructible
ZoneBatiment --|> ZoneConstructible
Territoire --- ZoneBatiment : [2:3]
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Enfin, ici, nous aurons toutes nos attributs et méthodes importants de notre classe.


@enduml
