@startuml
start
while (zone mer disponible?)
  #PaleGreen:prendre une zone mer aléatoirement;
  :placer la zone mer;
endwhile
while (territoire disponible?)
  #PaleGreen:prendre un territoire aléatoirement;
  :placer le territoire en spirale dans le sens horraire;
endwhile
while (jeton disponible?)
  #PaleGreen:Placer les jetons dans l’ordre lexicographique en escargot dans le sens horraire;
endwhile
:Placer le voleur sur la case désert;
while (joueur disponible?)
  #PaleGreen:reçoit une fiche Coûts de construction;
  :reçoit toutes les pièces de jeu de sa couleur;
  :place une colonie et une route;
  :place une étoile sur cette première colonie;
endwhile
while (joueur disponible?)
  #PaleGreen:place une colonie et une route;
  :reçoit pour sa colonie marquée d’une étoile sa première production;
endwhile
:placement fiches spéciales;
:placement carte ressource;
:placement carte développement;
stop
@enduml
